radiorabe/suisa_sendemeldung

.travis.yml
.travis/rpm.sh

This is a very simple travis-ci config that just adds build testing for the docker and rpm deliverables.
I hacked this together after giving renovate access to make it's onboarding pr and then realizing that we should have at least some safeguards in place when we merge renovate prs.
@am5z Have you considered how you we want to test the python code long term? This just focuses on the build parts but could easily get extended to also cover the python code. 
I also built [these](https://hub.docker.com/r/radiorabe/suisa_sendemeldung/) to act as a build cache, but that's just me over engineering things.

Configure travis-ci

---

.travis/rpm.sh

Reverts radiorabe/suisa_sendemeldung#27
It would be better to add python3-devel to BuildRequires in the specfile

Revert "fix build"

---

suisa_sendemeldung.spec

The build failed because the rpm macros %py3_* are provided by a dependency of python3-devel

add python3-devel to BuildRequires

---

suisa_sendemeldung/suisa_sendemeldung.py

pass recipients, cc and bcc as is to `create_message` (no split, no join)

---

.github/workflows/release.yaml
README.md

Our container environment is already having issues with the newly introduced [download rate limit](https://docs.docker.com/docker-hub/download-rate-limit/) so I am migrating all our images to the GitHub Container Registry.
I've already prepared the secret needed to logon to the registry so this will build and push images on `master` after we merge it.

chore(container image): migrate to ghcr.io

---

.github/workflows/release.yaml

Replaces `crazy-max/ghaction-docker-meta` with it's new replacement `docker/metadata-action`.
It's the same action but it got adopted by the folks managing the `docker` orga on GitHub.
Fixes #71

chore(ci): replace crazy-max/ghaction-docker-meta with docker/metadata-action

---

suisa_sendemeldung/acrclient.py

This should basically never happen unless somthing is bad between us and acr cloud.

fix: timeout acr requests after 10 seconds

---

suisa_sendemeldung/acrclient.py
suisa_sendemeldung/suisa_sendemeldung.py
tests/test_suisa_sendemeldung.py

As seen in #200, we have `custom_files` where the artists are represented by a single string instead of a list. This PR handles this issue correctly.

fix: handle artists from custom_files

---

requirements.txt
suisa_sendemeldung/suisa_sendemeldung.py
tests/test_suisa_sendemeldung.py

Uses the new [iso3901](https://github.com/Tagger-phile/py-iso3901) to validate our ISRC records before publishing, thus ensuring that we don't send any garbage provided to us. The linked ticket has a description of the amount of records affected by this and shows why the implementation in this PR should suffice for our needs.
* fixes #205

feat: only include valid iso3901 ISRC fields in output

---

requirements.txt
setup.cfg
suisa_sendemeldung/suisa_sendemeldung.py
tests/test_suisa_sendemeldung.py

Includes a huge new amount of fields as per the tariff and also updates our code to directly include a german email template.
Having the template in code should help us closely manage future change to it should we need to adopt it if the tariff gets updated.
There are also a bunch of fields that acr-cloud doesn't currently deliver, but most of those are not in the "official" list as per the tariff and only in the example.
This drafts what i'm hoping will fix most stuff...
* fixes #187 
* fixes #188

feat: standardize output and add many fields

---

suisa_sendemeldung/suisa_sendemeldung.py
tests/test_suisa_sendemeldung.py

This is specific to our custom bucket, but the code for music and custom buckets is currently shared in both implementation paths.

fix: support strings in album field

---

suisa_sendemeldung/suisa_sendemeldung.py

There are a few cases where the release date isn't set at all and this takes care of putting `""` instead of `None` into our output.

fix: handle release_date==None case

---

.github/workflows/release.yaml
.github/workflows/semantic-release.yaml
README.md

This automates tagging new versions and starts publishing versioned artifacts. I'm also adding pypi as a deployment target (because we can). I already prepped the needed secrets in the @radiorabe orga. If all goes well then merging this will cause a `v0.4.0` tag to be created and published.

chore: cd pipeline with semantic release and publish

---

.github/workflows/release.yaml

It was missing some labels so the image wasn't properly linked with the repo leading to a denied push.
I reconfigure packages to allow the push, this fixes it so nothing similar happens in future.
While i was at it i also added a bunch of other standard labels that most other images have.

fix: add labels for container image

---

suisa_sendemeldung/suisa_sendemeldung.py

For January 1st it would format the year wrong. Documentation is here: https://babel.pocoo.org/en/latest/dates.html#date-fields
```python
>>> from babel.dates import format_date
>>> from datetime import datetime
>>> d = datetime(year=2023, month=1, day=1)
>>> format_date(d,format="YYYY")
'2022'
>>> format_date(d,format="yyyy")
'2023'
```

fix: date formatting iso year-week calender

---

suisa_sendemeldung/suisa_sendemeldung.py
tests/test_suisa_sendemeldung.py

SUISA wants the duration field formatted as hh:mm.ss

fix: format duration according to SUISA requirements

---

suisa_sendemeldung/suisa_sendemeldung.py

Changes the default email subject from `SUISA Sendemeldung` to something like `SUISA Sendemeldung von Radio Bern RaBe für 2023-01`.

fix: change default email subject

---

setup.py

This should also fix the issues with pushing to the package registry as it always generates a new version based on the Git tag
```shell
$ python3 setup.py --version
0.8.2.dev1+g40c6282
```

feat: use setuptools_scm to set version of python package

---

suisa_sendemeldung/suisa_sendemeldung.py
tests/test_suisa_sendemeldung.py

fix: handle unexpected release date

---

suisa_sendemeldung/suisa_sendemeldung.py
tests/test_suisa_sendemeldung.py

I opted for allowing stream_id to have 10 chars assuming that needing to allow 11 will not happen soon.
* fixes #393

fix: Allow stream_id to be 9-10 chars

---

suisa_sendemeldung/suisa_sendemeldung.py
tests/__snapshots__/test_suisa_sendemeldung.ambr
tests/test_suisa_sendemeldung.py

This makes it possible to generate reports without using cridlib, mainly because cridlib only supports rabe.ch domains for the forseeable future. The alternative output is a based on the same data but simplified to not contain any rabe specific info.

feat: Add --crid-mode flag to bypass cridlib
